project:
  name: etl_ibm
  ports:
    webserver: 8080

env:
  - API_KEY=${API_KEY}
  - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
  - AZURE_CONTAINER_NAME=${AZURE_CONTAINER_NAME}
  - DB_USER=${DB_USER}
  - DB_PASSWORD=${DB_PASSWORD}
  - DB_HOST=${DB_HOST}
  - DB_NAME=${DB_NAME}
  - DB_PORT=${DB_PORT}
